spring:
  application:
    name: sunyi-cloud-zuul
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-robbin:
      path: /api/robbin/**
      serviceId: sunyi-cloud-robbin
    api-feign:
      path: /api/feign/**
      serviceId: sunyi-cloud-feign
